routes/web.php
        Route::delete('/people/{contact}/pet/{pet}', 'Contacts\\PetsController@trash');
        Route::get('/petcategories', 'Contacts\\PetsController@getPetCategories');

        // Reminders
        Route::get('/people/{contact}/reminders/add', 'Contacts\\RemindersController@create')->name('.reminders.add');
        Route::post('/people/{contact}/reminders/store', 'Contacts\\RemindersController@store')->name('.reminders.store');
        Route::get('/people/{contact}/reminders/{reminder}/edit', 'Contacts\\RemindersController@edit')->name('.reminders.edit');
        Route::put('/people/{contact}/reminders/{reminder}', 'Contacts\\RemindersController@update')->name('.reminders.update');
        // Special route to delete reminders. In one migration in summer '17, I
        // accidentely f**ked up the reminders table by messing up the contact ids
        // and now the only way to delete those reminders is to bypass the ReminderRequest
        // by creating a new route.
        Route::delete('/people/{contact}/reminders/{rmd}', 'Contacts\\RemindersController@destroy')->name('.reminders.delete');

        // Tasks
        Route::get('/people/{contact}/tasks', 'Contacts\\TasksController@get');
        Route::post('/people/{contact}/tasks', 'Contacts\\TasksController@store');
        Route::post('/people/{contact}/tasks/{task}/toggle', 'Contacts\\TasksController@toggle');
        Route::put('/people/{contact}/tasks/{task}', 'Contacts\\TasksController@update');
        Route::delete('/people/{contact}/tasks/{task}', 'Contacts\\TasksController@destroy')->name('.tasks.delete');

        // Gifts
        Route::get('/people/{contact}/gifts', 'Contacts\\GiftsController@get');
        Route::post('/people/{contact}/gifts/{gift}/toggle', 'Contacts\\GiftsController@toggle');
        Route::get('/people/{contact}/gifts/add', 'Contacts\\GiftsController@create')->name('.gifts.add');
        Route::get('/people/{contact}/gifts/{gift}/edit', 'Contacts\\GiftsController@edit');
        Route::post('/people/{contact}/gifts/store', 'Contacts\\GiftsController@store')->name('.gifts.store');
        Route::post('/people/{contact}/gifts/{gift}/update', 'Contacts\\GiftsController@update')->name('.gifts.update');
        Route::delete('/people/{contact}/gifts/{gift}', 'Contacts\\GiftsController@destroy')->name('.gifts.delete');

        // Debt
        Route::get('/people/{contact}/debt/add', 'Contacts\\DebtController@create')->name('.debt.add');
        Route::post('/people/{contact}/debt/store', 'Contacts\\DebtController@store')->name('.debt.store');
        Route::get('/people/{contact}/debt/{debt}/edit', 'Contacts\\DebtController@edit')->name('.debt.edit');
        Route::put('/people/{contact}/debt/{debt}', 'Contacts\\DebtController@update')->name('.debt.update');
        Route::delete('/people/{contact}/debt/{debt}', 'Contacts\\DebtController@destroy')->name('.debt.delete');

        // Phone calls
        Route::post('/people/{contact}/call/store', 'Contacts\\CallsController@store')->name('.call.store');
        Route::delete('/people/{contact}/call/{call}', 'Contacts\\CallsController@destroy')->name('.call.delete');

        // Search
        Route::post('/people/search', 'ContactsController@search')->name('people.search');

        // Stay in touch information
        Route::post('/people/{contact}/stayintouch', 'ContactsController@stayInTouch');
    });

    // Activities
    Route::group(['as' => 'activities'], function () {
        Route::get('/activities/add/{contact}', 'ActivitiesController@create')->name('.add');
        Route::post('/activities/store/{contact}', 'ActivitiesController@store')->name('.store');
        Route::get('/activities/{activity}/edit/{contact}', 'ActivitiesController@edit')->name('.edit');
        Route::put('/activities/{activity}/{contact}', 'ActivitiesController@update')->name('.update');
        Route::delete('/activities/{activity}', 'ActivitiesController@destroy')->name('.delete');
    });

    Route::group(['as' => 'journal'], function () {
        Route::get('/journal', ['as' => '.index', 'uses' => 'JournalController@index']);
        Route::get('/journal/entries', 'JournalController@list')->name('.list');
        Route::get('/journal/entries/{journalEntry}', 'JournalController@get');
        Route::get('/journal/hasRated', 'JournalController@hasRated');
        Route::post('/journal/day', 'JournalController@storeDay');
        Route::delete('/journal/day/{day}', 'JournalController@trashDay');

        Route::get('/journal/add', ['as' => '.create', 'uses' => 'JournalController@create']);
        Route::post('/journal/create', ['as' => '.create', 'uses' => 'JournalController@save']);
        Route::delete('/journal/{entryId}', 'JournalController@deleteEntry');
    });

    Route::group(['as' => 'settings'], function () {
        Route::get('/settings', ['as' => '.index', 'uses' => 'SettingsController@index']);
        Route::post('/settings/delete', ['as' => '.delete', 'uses' => 'SettingsController@delete']);
        Route::post('/settings/reset', ['as' => '.reset', 'uses' => 'SettingsController@reset']);
        Route::post('/settings/save', 'SettingsController@save');
        Route::get('/settings/export', 'SettingsController@export')->name('.export');
        Route::get('/settings/exportToSql', 'SettingsController@exportToSQL');

        Route::get('/settings/personalization', 'Settings\\PersonalizationController@index')->name('.personalization');
        Route::get('/settings/personalization/contactfieldtypes', 'Settings\\PersonalizationController@getContactFieldTypes');
        Route::post('/settings/personalization/contactfieldtypes', 'Settings\\PersonalizationController@storeContactFieldType');
        Route::put('/settings/personalization/contactfieldtypes/{contactfieldtype_id}', 'Settings\\PersonalizationController@editContactFieldType');
        Route::delete('/settings/personalization/contactfieldtypes/{contactfieldtype_id}', 'Settings\\PersonalizationController@destroyContactFieldType');

        Route::get('/settings/personalization/genders', 'Settings\\GendersController@getGenderTypes');
        Route::post('/settings/personalization/genders', 'Settings\\GendersController@storeGender');
        Route::put('/settings/personalization/genders/{gender}', 'Settings\\GendersController@updateGender');
        Route::delete('/settings/personalization/genders/{gender}/replaceby/{gender_id}', 'Settings\\GendersController@destroyAndReplaceGender');
        Route::delete('/settings/personalization/genders/{gender}', 'Settings\\GendersController@destroyGender');

        Route::get('/settings/personalization/reminderrules', 'Settings\\ReminderRulesController@get');
        Route::post('/settings/personalization/reminderrules/{reminderRule}', 'Settings\\ReminderRulesController@toggle');

        Route::get('/settings/personalization/modules', 'Settings\\ModulesController@get');
        Route::post('/settings/personalization/modules/{module}', 'Settings\\ModulesController@toggle');

        Route::get('/settings/import', 'SettingsController@import')->name('.import');
        Route::get('/settings/import/report/{importjobid}', 'SettingsController@report')->name('.report');
        Route::get('/settings/import/upload', 'SettingsController@upload')->name('.upload');
        Route::post('/settings/import/storeImport', 'SettingsController@storeImport')->name('.storeImport');

        Route::get('/settings/users', 'SettingsController@users')->name('.users');
        Route::get('/settings/users/add', 'SettingsController@addUser')->name('.users.add');
        Route::delete('/settings/users/{user}', ['as' => '.users.delete', 'uses' => 'SettingsController@deleteAdditionalUser']);
        Route::post('/settings/users/save', 'SettingsController@inviteUser')->name('.users.save');
        Route::delete('/settings/users/invitations/{invitation}', 'SettingsController@destroyInvitation');

        Route::get('/settings/subscriptions', 'Settings\\SubscriptionsController@index')->name('.subscriptions.index');
        Route::get('/settings/subscriptions/upgrade', 'Settings\\SubscriptionsController@upgrade')->name('.subscriptions.upgrade');
        Route::get('/settings/subscriptions/upgrade/success', 'Settings\\SubscriptionsController@upgradeSuccess')->name('.subscriptions.upgrade.success');
        Route::post('/settings/subscriptions/processPayment', 'Settings\\SubscriptionsController@processPayment');
        Route::get('/settings/subscriptions/invoice/{invoice}', 'Settings\\SubscriptionsController@downloadInvoice');
        Route::get('/settings/subscriptions/downgrade', 'Settings\\SubscriptionsController@downgrade')->name('.subscriptions.downgrade');
        Route::post('/settings/subscriptions/downgrade', 'Settings\\SubscriptionsController@processDowngrade');
        Route::get('/settings/subscriptions/downgrade/success', 'Settings\\SubscriptionsController@downgradeSuccess')->name('.subscriptions.upgrade.success');

        Route::get('/settings/tags', 'SettingsController@tags')->name('.tags');
        Route::get('/settings/tags/add', 'SettingsController@addUser')->name('.tags.add');
        Route::delete('/settings/tags/{user}', ['as' => '.tags.delete', 'uses' => 'SettingsController@deleteTag']);

        Route::get('/settings/api', 'SettingsController@api')->name('.api');

        // Security
        Route::get('/settings/security', 'SettingsController@security')->name('.security');
        Route::post('/settings/security/passwordChange', 'Auth\\PasswordChangeController@passwordChange');
        Route::get('/settings/security/2fa-enable', 'Settings\\MultiFAController@enableTwoFactor')->name('.security.2fa-enable');
        Route::post('/settings/security/2fa-enable', 'Settings\\MultiFAController@validateTwoFactor');
        Route::get('/settings/security/2fa-disable', 'Settings\\MultiFAController@disableTwoFactor')->name('.security.2fa-disable');

app/Call.php
<?php

namespace App;

use Parsedown;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Call extends Model
{
    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id'];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['called_at'];

    /**
     * Get the account record associated with the gift.
     *
     * @return BelongsTo
     */
    public function account()
    {
        return $this->belongsTo(Account::class);
    }

    /**
     * Get the contact record associated with the gift.
     *
     * @return BelongsTo
     */
    public function contact()
    {
        return $this->belongsTo(Contact::class);
    }

    /**
     * Return the markdown parsed body.
     *
     * @return string
     */
    public function getParsedContentAttribute()
    {
        if (is_null($this->content)) {
            return;
        }

        return (new Parsedown())->text($this->content);
    }
}

resources/views/people/modal/activity_view.blade.php
<!-- Modal -->
<div class="modal log-call fade" id="activity{{$activity->id}}Modal" tabindex="-1">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        {{ $activity->getSummary() }}
        <button type="button" class="close {{ \App\Helpers\LocaleHelper::getDirection() }}" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

              <label for="summary">{{ trans('people.activities_who_was_involved') }}</label>
                  <ul class="contacts">
                      <ul class="contacts-list">
                          @foreach ($activity->contacts as $contact)
                              <li class="pretty-tag"><a href="/people/{{ $contact->hashID() }}">{{ $contact->first_name }} {{ $contact->last_name }}</a></li>
                          @endforeach
                      </ul>
                  </ul>
                  <br>

                  <label for="date_it_happened">{{ trans('people.activities_add_date_occured') }}</label>
                  <p>{{ $activity->date_it_happened->format('Y-m-d') }}</p>
                  <br>

                  <label for="activity_type_id">{{ trans('people.activities_activity') }}</label>
                  @if (isset($activity->type))
                     <p>{{ trans('people.activity_type_'.$activity->type->key) }}</p>
                  @else
                     <p>{{ trans('app.unknown')}}</p>
                  @endif
                  <br>

                  <label for="description">{{ trans('people.activities_add_optional_comment') }}</label>
                  <div class="markdown">
                  {!! $activity->parsed_content !!}
                  </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ trans('app.close') }}</button>
      </div>
    </div>
  </div>
</div>

resources/views/people/modal/log_call.blade.php
<!-- Modal -->
<div class="modal log-call fade" id="logCallModal" tabindex="-1">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{{ trans('people.modal_call_title') }}</h5>
        <button type="button" class="close {{ \App\Helpers\LocaleHelper::getDirection() }}" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" action="/people/{{ $contact->hashID() }}/call/store">
          {{ csrf_field() }}

          <div class="form-group">
            <label for="content" class="form-control-label b">{{ trans('people.modal_call_comment') }}</label>
            <textarea class="form-control mb3" name="content" id="content" maxlength="2500" autofocus>
            </textarea>

            <p class="f6">{{ trans('app.markdown_description')}} <a href="https://guides.github.com/features/mastering-markdown/" target="_blank">{{ trans('app.markdown_link') }}</a></p>

            <p class="date-it-happened">
              {{ trans('people.modal_call_date') }} <a href="#" class="change-date-happened">{{ trans('people.modal_call_change') }}</a>
            </p>

            <p class="exact-date">
              {{ trans('people.modal_call_exact_date') }}
              <input type="date" name="called_at" class="form-control"
                           value="{{ now()->format('Y-m-d') }}"
                           min="{{ now(Auth::user()->timezone)->subYears(120)->format('Y-m-d') }}"
                           max="{{ now(Auth::user()->timezone)->format('Y-m-d') }}">
            </p>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ trans('app.cancel') }}</button>
        <button type="button" class="btn btn-primary modal-cta">{{ trans('app.save') }}</button>
      </div>
    </div>
  </div>
</div>